steps:
  - label: ":sparkles: Hello Buildkite"
    commands:
      - echo "🐝 Starting up..."
      - echo "Running a few cool things..."
      - echo "First line of output"
      - echo "Second line of output"
      - echo "✅ Done!"
      - buildkite-agent annotate "🎉 Build complete!<br>Everything ran smoothly!" --style "success"
