steps:
  - label: "Failing Step"
    command: |
      echo "EXIT_CODE=3" >> "$BUILDKITE_ENV_FILE"
      exit 3

  - label: "Trigger if EXIT_CODE=3"
    depends_on: ~
    allow_dependency_failure: true
    command: |
      if [ "$EXIT_CODE" = "3" ]; then
        buildkite-agent pipeline upload <<EOF
        steps:
          - trigger: "training-1/starter-pipeline-2"
            async: true
