steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build

  - label: ":x: Intentional Failure"
    command: |
      echo "This will fail intentionally to trigger cancel_on_build_failing"
      exit 1
    cancel_on_build_failing: true

  - label: ":hammer: Tests"
    commands:
      - "npm install"
      - "npm run tests"
    branches: "main"
    env:
      NODE_ENV: "test"
    parallelism: 3
    retry:
      automatic:
        - exit_status: 1
          limit: 2
    cancel_on_build_failing: true
    key: tests

  - label: ":repeat: Retry Tests"
    command: |
      if [ "$BUILDKITE_RETRY_COUNT" -gt 0 ]; then
        echo "Retrying tests..."
        npm install && npm run tests;
      else
        echo "Not a retry. Skipping this step.";
        exit 0;
      fi
    cancel_on_build_failing: false  # Ensure this step is not fast-failed
