steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build

  - label: ":x: Intentional Failure"
    command: |
      echo "This will fail intentionally to trigger cancel_on_build_failing";
      exit 1
    cancel_on_build_failing: true  # Enable fast fail

  - label: ":hammer: Tests"
    commands:
      - "npm install"
      - "npm run tests"
    branches: "main"
    env:
      NODE_ENV: "test"
    parallelism: 3  # To observe cancellations in parallel
    retry:
      automatic:
        - exit_status: 1
          limit: 2
    cancel_on_build_failing: true  # Ensure this step respects fast fail

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the rocket"
    depends_on: build
    cancel_on_build_failing: true  # Ensure this step is also subject to fast fail
