steps:
  - label: ":test_tube: %{matrix.test_name}"
    command: |
      echo -e "\033[36mRunning %{matrix.test_name}...\033[0m"

      if [ "%{matrix.test_name}" = "fail-me-softly" ]; then
        echo -e "\033[31m❌ Simulating soft failure...\033[0m"
        exit 1
      else
        echo -e "\033[32m✅ Success!\033[0m"
      fi
    matrix:
      test_name:
        - pass-one
        - pass-two
        - fail-me-softly
      adjustments:
        - with:
            test_name: fail-me-softly
          soft_fail: true
