steps:
  - label: "Failing Step"
    soft_fail: true
    command: |
      echo "EXIT_CODE=3" >> "$BUILDKITE_ENV_FILE"
      exit 3  # Step fails, but pipeline continues

  - label: "Trigger if EXIT_CODE=3"
    command: |
      if [ "$EXIT_CODE" = "3" ]; then
        echo 'steps:
          - label: "Triggered pipeline"
            trigger: "training/starter-pipeline-2"' | buildkite-agent pipeline upload
      fi
