steps:
  - label: ":memo: Annotation Test"
    command: |
      echo "Testing Bk annotation..."
      buildkite-agent annotate "✅ Annotation works!<br>This is a test message from the pipeline." --style "success"

