steps:
  - label: "Deploy us-west-2"
    command: echo "Deploying us-west-2"
    key: us_west_2

  - wait: ~  # First wait step

  - label: "Deploy eu-west"
    command: echo "Deploying eu-west"
    key: eu_west

  - wait: ~  # Second wait step

  - label: "Deploy ap-southeast-2"
    command: echo "Deploying ap-southeast-2"
    key: ap_southeast_2

  - label: "Deploy us-east-1"
    command: echo "Deploying us-east-1"
    key: us_east
