steps:
  - label: ":test_tube: Testing %{ENV}"
    command: |
      echo -e "\033[36m🔍 Running tests for $ENV...\033[0m"

      if [ "$ENV" = "two" ]; then
        echo -e "\033[31m❌ Simulated failure in $ENV\033[0m"
        buildkite-agent annotate "❌ Failed in <b>$ENV</b>" --style "error" --context "$ENV"
        exit 1
      else
        echo -e "\033[32m✅ Success in $ENV\033[0m"
        buildkite-agent annotate "✅ Passed in <b>$ENV</b>" --style "success" --context "$ENV"
      fi
    matrix:
      ENV:
        - one
        - two
        - three
