steps:
  - label: "First step"
    command: |
      echo "EXIT_CODE=3" >> "$BUILDKITE_ENV_FILE"
      exit 3

  - label: "Second step"
    if: build.env("EXIT_CODE") == "3"
    command: |
      buildkite-agent pipeline upload <<EOF
      steps:
        - trigger: "training/starter-pipeline-2"
          async: true
      EOF
