---
notify:
  - slack:
      channels: [U07U3PFDC65, buildkite#test-slack-notifications]
    if: build.state == "started"  # Trigger on build start
  - slack:
      channels: [U07U3PFDC65, buildkite#test-slack-notifications]
    if: build.state == "passed" || build.state == "failed"  # Pass/fail notifications
