steps:
  - label: ":mag: Check for new commits"
    command: "./check-new-commits.sh"
    key: commit-check

  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build
    depends_on: commit-check
    allow_dependency_failure: true

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build
    allow_dependency_failure: true

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the rocket"
      cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
    key: deploy
    depends_on: test
    allow_dependency_failure: true
