steps:
  - label: ":construction_worker: Build"
    commands:
      - |
        # Get timestamps (fallback to current UNIX time if missing)
        job_started="${BUILDKITE_JOB_STARTED_AT:-$(date -u +%s)}"
        build_created="${BUILDKITE_BUILD_CREATED_AT:-$(date -u +%s)}"

        # Convert timestamps to integers
        job_started_ts=$((job_started))
        build_created_ts=$((build_created))

        # Calculate queue time
        time_in_queue=$(( job_started_ts - build_created_ts ))

        # Annotate if queued for over 5 minutes
        if [ "$time_in_queue" -gt 300 ]; then
          buildkite-agent annotate "⚠️ Queued for $((time_in_queue / 60)) minutes before starting." --style "warning"
        fi

        echo "🚀 Build the rocket"
    key: build
