steps:
  - label: "First step"
    key: "failing-step"
    commands:
      - echo "First step failing..."
      - exit 3

  - label: "Second step"
    key: "trigger-step"
    # This ensures Step 2 runs even if Step 1 fails
    depends_on: ~
    commands:
      - echo "Second step running!"
      - buildkite-agent pipeline upload <<EOF
steps:
  - label: "Async trigger"
    trigger: "training-1/starter-pipeline-2"
    async: true

