steps:
 - label: "Failing Step"
   soft_fail: true
   command: |
     buildkite-agent meta-data set exit-code 3
     exit 3

 - label: "Trigger if EXIT_CODE=3"
   command: |
     if [ "$(buildkite-agent meta-data get exit-code)" = "3" ]; then
       echo 'steps:
         - trigger: "training-1/starter-pipeline-2"' | buildkite-agent pipeline upload
     fi
