steps:
  - label: "Lock Test - First Process"
    command: ".buildkite/lock-test-1.sh"

  - label: "Lock Test - Second Process"
    command: ".buildkite/lock-test-2.sh"


#testing only to see if script is executable files not yet added 
