steps:
  - label: "First step"
    command: |
      echo "First step failing..."
      exit 3

  - label: "Second step"
    if: build.env("BUILDKITE_COMMAND_EXIT_STATUS") == "3"
    command: |
      echo "Second step running!"
      buildkite-agent pipeline upload <<EOF
      steps:
        - trigger: "training/starter-pipeline-2"
          async: true
      EOF
