steps:
  - label: ":sparkles: Hello Buildkite with Colors"
    commands:
      - echo -e "\033[33m🐝 Starting up...\033[0m"
      - echo -e "\033[36mRunning a few cool things...\033[0m"
      - echo -e "\033[35mFirst line of output\033[0m"
      - echo -e "\033[34mSecond line of output\033[0m"
      - echo -e "\033[32m✅ Done!\033[0m"
      - buildkite-agent annotate "🎉 Build complete!<br>Everything ran smoothly!" --style "success"
