steps:
  - label: ":construction_worker: Build"
    commands:
      - START_TIME=$(date +%s)
      - QUEUE_TIME=$(( START_TIME - ${BUILDKITE_BUILD_CREATED_AT:-$START_TIME} ))
      - if [ "$QUEUE_TIME" -gt 300 ]; then buildkite-agent annotate "тЪая╕П Queue time: $((QUEUE_TIME/60)) minutes" --style "warning"; fi
      - echo "ЁЯЪА Build the rocket"
    key: build
