steps:
  - label: ":one: Step One"
    command: echo "Running Step One"
    key: step_one

  - label: ":two: Step Two"
    command: echo "Running Step Two"
    key: step_two

  - label: ":three: Step Three"
    command: echo "Running Step Three"
    key: step_three
    depends_on: step_one

  - label: ":four: Step Four"
    command: echo "Running Step Four"
    key: step_four
    depends_on: step_two
