steps:
  - label: "foo"
    command: |
      echo "Running..."
      buildkite-agent pipeline upload <<EOF
      steps:
        - label: "Async step"
          trigger: "training-1/starter-pipeline-2"  
          async: true
      EOF
      exit 3
