steps:
  - label: ":cat: Say Meow"
    command: |
      echo "--- Sending some cuteness"
      cat <<'EOF' > cat.txt
 /\_/\  
( o.o ) 
 > ^ <   Meow! Your build is purr-fect!
EOF
      buildkite-agent annotate "$(cat cat.txt)" --style "success"

