steps:
  - label: "Test Starter2 Git Mirror"
    commands:
      - mkdir -p ~/test-git-mirrors
      - git clone --mirror https://github.com/amnabk/starter.git ~/test-git-mirrors/starter.git
      - git clone --reference ~/test-git-mirrors/starter.git https://github.com/amnabk/starter.git ~/test-starter-clone
      - cd ~/test-starter-clone && git remote -v

