steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build

  - label: ":x: Intentional Failure"
    command: |
      echo "This will fail intentionally to trigger cancel_on_build_failing";
      exit 1
    cancel_on_build_failing: true

  - label: "Dynamic Retry Handling"
    command: |
      if [ "$BUILDKITE_RETRY_COUNT" -gt 0 ]; then
        echo "Re-uploading pipeline for retry...";
        buildkite-agent pipeline upload .buildkite/retry-pipeline.yml;
      else
        echo "Skipping retry pipeline upload.";
      fi
    key: retry-handler
