steps:
  - label: "Upload and Trigger"
    command: |
      buildkite-agent artifact upload "$some_artifact"
      buildkite-agent pipeline upload <<EOF
      steps:
        - trigger: "training-1/starter-pipeline-2"
          async: true
      EOF

  - label: "Handle Failure"
    command: exit 3
