steps:
  - label: ":hammer: Simulated Tests for %{ENVIRONMENT}"
    command: |
      echo -e "\033[36m🔍 Running tests in $ENVIRONMENT...\033[0m"

      if [ "$ENVIRONMENT" = "two" ]; then
        echo -e "\033[31m❌ Tests failed in $ENVIRONMENT\033[0m"
        buildkite-agent annotate "❌ Tests failed in <b>$ENVIRONMENT</b>" --style "error" --context "$ENVIRONMENT"
        exit 1
      else
        echo -e "\033[32m✅ Tests passed in $ENVIRONMENT\033[0m"
        buildkite-agent annotate "✅ Tests passed in <b>$ENVIRONMENT</b>" --style "success" --context "$ENVIRONMENT"
      fi
    matrix:
      env:
        ENVIRONMENT:
          - one
          - two
          - three
