steps:
  - label: ":construction_worker: Build"
    commands:
      - |
        # Record start time
        START_TIME=$(date +%s)
        
        echo "🚀 Build the rocket"
        
        # Record end time and calculate duration
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        
        # Add note if it ran quickly (less than 30 seconds)
        if [ "$DURATION" -lt 30 ]; then
          buildkite-agent annotate "⚡ Build finished in ${DURATION} seconds - likely skipped" --style "info"
        fi
