steps:
  - command: |
      echo -e "\033[36m🔍 Running tests for $BUILDKITE_ENV...\033[0m"

      if [ "$BUILDKITE_ENV" = "two" ]; then
        echo -e "\033[31m❌ Simulated failure in $BUILDKITE_ENV\033[0m"
        buildkite-agent annotate "❌ Failed in <b>$BUILDKITE_ENV</b>" --style "error" --context "$BUILDKITE_ENV"
        exit 1
      else
        echo -e "\033[32m✅ Success in $BUILDKITE_ENV\033[0m"
        buildkite-agent annotate "✅ Passed in <b>$BUILDKITE_ENV</b>" --style "success" --context "$BUILDKITE_ENV"
      fi
    label: ":test_tube: Testing %{BUILDKITE_ENV}"
    matrix:
      setup:
        - BUILDKITE_ENV: one
        - BUILDKITE_ENV: two
        - BUILDKITE_ENV: three
