steps:
  - label: ":construction_worker: Build"
    commands:
      - |
        # Calculate queue time in minutes
        queue_time=$(( (${BUILDKITE_JOB_STARTED_AT:-$(date +%s)} - ${BUILDKITE_BUILD_CREATED_AT:-$(date +%s)}) / 60 ))
        
        # Add warning if queued more than 5 minutes
        if [ "$queue_time" -gt 5 ]; then
          buildkite-agent annotate "тЪая╕П Queued for ${queue_time} minutes" --style "warning"
        fi
        
        echo "ЁЯЪА Build the rocket"
    key: build
